import { defineConfig } from "vitepress";
import { defineTeekConfig } from "vitepress-theme-teek/config";

const teekConfig = defineTeekConfig({
  teekHome: false,
  vpHome: true,
  sidebarTrigger: true,
  author: { name: "AppPorts" },
  footerInfo: {
    topMessage: ["External drives save the world!"],
    bottomMessage: [
      '<div style="display:flex;gap:20px;justify-content:center;flex-wrap:wrap"><a href="https://github.com/wzh4869/AppPorts" target="_blank">GitHub</a><a href="https://deepwiki.com/wzh4869/AppPorts" target="_blank">DeepWiki</a><a href="https://github.com/wzh4869/AppPorts/releases" target="_blank">Releases</a></div>',
    ],
    theme: {
      name: "Theme By Teek",
      link: "https://github.com/Kele-Bingtang/vitepress-theme-teek",
    },
    copyright: {
      createYear: 2025,
      suffix: "AppPorts",
      link: "https://github.com/wzh4869/AppPorts",
    },
  },
  codeBlock: {
    copiedDone: (TkMessage: any) => TkMessage.success("Copied!"),
  },
  articleShare: { enabled: false },
  articleAnalyze: { showInfo: false, showDate: false, showWord: false, showReadingTime: false },
  vitePlugins: {
    sidebar: false,
    mdH1: false,
    docAnalysis: false,
    permalink: false,
    autoFrontmatter: false,
  },
});

export default defineConfig({
  extends: teekConfig,
  title: "AppPorts",
  description: "User Guide",
  lastUpdated: true,
  cleanUrls: false,

  head: [
    ["link", { rel: "icon", type: "image/png", href: "/logo.png" }],
    ["script", { defer: true, src: "https://cloud.umami.is/script.js", "data-website-id": "2f0679ac-f605-4a76-9a55-11681b47cef5" }],
  ],

  locales: {
    root: {
      label: "简体中文",
      lang: "zh-Hans",
      title: "AppPorts",
      description: "用户指南",
      themeConfig: {
        logo: "/logo.png",
        darkModeSwitchLabel: "主题",
        sidebarMenuLabel: "菜单",
        returnToTopLabel: "返回顶部",
        lastUpdatedText: "最后更新于",
        outline: { level: [2, 3], label: "目录" },
        docFooter: { prev: "上一篇", next: "下一篇" },
        search: { provider: "local", options: { translations: { button: { buttonText: "搜索", buttonAriaLabel: "搜索" }, modal: { noResultsText: "无法找到相关结果", resetButtonTitle: "清除查询条件", footer: { selectText: "选择", navigateText: "切换", closeText: "关闭" } } } } },
        editLink: { pattern: "https://github.com/wzh4869/AppPorts/edit/main/User_docs/docs/:path", text: "在 GitHub 上编辑此页" },
        socialLinks: [{ icon: "github", link: "https://github.com/wzh4869/AppPorts" }],
        nav: [
          { text: "首页", link: "/" },
          { text: "快速开始", link: "/faststart" },
          { text: "下载", link: "https://github.com/wzh4869/AppPorts/releases" },
          { text: "更新日志", link: "/changelog" },
        ],
        sidebar: [
          {
            text: "指南",
            items: [
              { text: "简介", link: "/AppPorts" },
              { text: "快速开始", link: "/faststart" },
              { text: "核心功能", link: "/core" },
              { text: "状态徽章说明", link: "/badges" },
              { text: "数据迁移", items: [
                { text: "基础实现", link: "/datamigrae/baseinfo" },
                { text: "工具目录识别", link: "/datamigrae/tools" },
                { text: "操作指南", link: "/datamigrae/operation" },
                { text: "重签名与崩溃防护", link: "/datamigrae/resign" },
              ]},
              { text: "App迁移策略", items: [
                { text: "迁移策略", link: "/migration-strategy/portal" },
                { text: "应用类型与策略对照", link: "/migration-strategy/strategy-map" },
                { text: "自更新应用识别", link: "/migration-strategy/updater-detection" },
                { text: "App Store 应用更新策略", link: "/migration-strategy/appstore-update" },
              ]},
              { text: "设置", link: "/settings" },
              { text: "兼容性与限制", link: "/limitations" },
              { text: "故障排除", link: "/troubleshooting" },
              { text: "常见问题", link: "/faq" },
              { text: "外部存储指南", link: "/storage-guide" },
              { text: "日志与诊断", link: "/logging" },
              { text: "更新日志", link: "/changelog" },
              { text: "贡献者指南", link: "/contributing" },
            ],
          },
        ],
      },
    },

    en: {
      label: "English",
      lang: "en",
      title: "AppPorts",
      description: "User Guide",
      themeConfig: {
        logo: "/logo.png",
        darkModeSwitchLabel: "Theme",
        sidebarMenuLabel: "Menu",
        returnToTopLabel: "Back to top",
        lastUpdatedText: "Last updated",
        outline: { level: [2, 3], label: "On this page" },
        docFooter: { prev: "Previous", next: "Next" },
        search: { provider: "local", options: { translations: { button: { buttonText: "Search", buttonAriaLabel: "Search" }, modal: { noResultsText: "No results found", resetButtonTitle: "Clear search", footer: { selectText: "select", navigateText: "switch", closeText: "close" } } } } },
        editLink: { pattern: "https://github.com/wzh4869/AppPorts/edit/main/User_docs/docs/:path", text: "Edit this page on GitHub" },
        socialLinks: [{ icon: "github", link: "https://github.com/wzh4869/AppPorts" }],
        nav: [
          { text: "Home", link: "/en/" },
          { text: "Getting Started", link: "/en/faststart" },
          { text: "Download", link: "https://github.com/wzh4869/AppPorts/releases" },
          { text: "Changelog", link: "/en/changelog" },
        ],
        sidebar: [
          {
            text: "Guide",
            items: [
              { text: "Introduction", link: "/en/AppPorts" },
              { text: "Getting Started", link: "/en/faststart" },
              { text: "Core Features", link: "/en/core" },
              { text: "Status Badges", link: "/en/badges" },
              { text: "Data Migration", items: [
                { text: "Basic Implementation", link: "/en/datamigrae/baseinfo" },
                { text: "Tool Directory Detection", link: "/en/datamigrae/tools" },
                { text: "Operation Guide", link: "/en/datamigrae/operation" },
                { text: "Re-signing & Crash Prevention", link: "/en/datamigrae/resign" },
              ]},
              { text: "App Migration Strategy", items: [
                { text: "Migration Strategies", link: "/en/migration-strategy/portal" },
                { text: "App Types & Strategies", link: "/en/migration-strategy/strategy-map" },
                { text: "Self-Updater Detection", link: "/en/migration-strategy/updater-detection" },
              ]},
              { text: "Settings", link: "/en/settings" },
              { text: "Compatibility & Limitations", link: "/en/limitations" },
              { text: "Troubleshooting", link: "/en/troubleshooting" },
              { text: "FAQ", link: "/en/faq" },
              { text: "External Storage Guide", link: "/en/storage-guide" },
              { text: "Logging & Diagnostics", link: "/en/logging" },
              { text: "Changelog", link: "/en/changelog" },
              { text: "Contributing", link: "/en/contributing" },
            ],
          },
        ],
      },
    },

    "zh-Hant": {
      label: "繁體中文",
      lang: "zh-Hant",
      title: "AppPorts",
      description: "用戶指南",
      themeConfig: {
        logo: "/logo.png",
        darkModeSwitchLabel: "主題",
        sidebarMenuLabel: "選單",
        returnToTopLabel: "返回頂部",
        lastUpdatedText: "最後更新於",
        outline: { level: [2, 3], label: "目錄" },
        docFooter: { prev: "上一篇", next: "下一篇" },
        search: { provider: "local", options: { translations: { button: { buttonText: "搜尋", buttonAriaLabel: "搜尋" }, modal: { noResultsText: "無法找到相關結果", resetButtonTitle: "清除查詢條件", footer: { selectText: "選擇", navigateText: "切換", closeText: "關閉" } } } } },
        editLink: { pattern: "https://github.com/wzh4869/AppPorts/edit/main/User_docs/docs/:path", text: "在 GitHub 上編輯此頁" },
        socialLinks: [{ icon: "github", link: "https://github.com/wzh4869/AppPorts" }],
        nav: [
          { text: "首頁", link: "/zh-Hant/" },
          { text: "快速開始", link: "/zh-Hant/faststart" },
          { text: "下載", link: "https://github.com/wzh4869/AppPorts/releases" },
          { text: "更新日誌", link: "/zh-Hant/changelog" },
        ],
        sidebar: [
          {
            text: "指南",
            items: [
              { text: "簡介", link: "/zh-Hant/AppPorts" },
              { text: "快速開始", link: "/zh-Hant/faststart" },
              { text: "核心功能", link: "/zh-Hant/core" },
              { text: "狀態徽章說明", link: "/zh-Hant/badges" },
              { text: "資料遷移", items: [
                { text: "基礎實作", link: "/zh-Hant/datamigrae/baseinfo" },
                { text: "工具目錄識別", link: "/zh-Hant/datamigrae/tools" },
                { text: "操作指南", link: "/zh-Hant/datamigrae/operation" },
                { text: "重新簽名與崩潰防護", link: "/zh-Hant/datamigrae/resign" },
              ]},
              { text: "App遷移策略", items: [
                { text: "遷移策略", link: "/zh-Hant/migration-strategy/portal" },
                { text: "應用類型與策略對照", link: "/zh-Hant/migration-strategy/strategy-map" },
                { text: "自更新應用識別", link: "/zh-Hant/migration-strategy/updater-detection" },
              ]},
              { text: "設定", link: "/zh-Hant/settings" },
              { text: "相容性與限制", link: "/zh-Hant/limitations" },
              { text: "故障排除", link: "/zh-Hant/troubleshooting" },
              { text: "常見問題", link: "/zh-Hant/faq" },
              { text: "外部儲存指南", link: "/zh-Hant/storage-guide" },
              { text: "日誌與診斷", link: "/zh-Hant/logging" },
              { text: "更新日誌", link: "/zh-Hant/changelog" },
              { text: "貢獻者指南", link: "/zh-Hant/contributing" },
            ],
          },
        ],
      },
    },

    ja: {
      label: "日本語",
      lang: "ja",
      title: "AppPorts",
      description: "ユーザーガイド",
      themeConfig: {
        logo: "/logo.png",
        darkModeSwitchLabel: "テーマ",
        sidebarMenuLabel: "メニュー",
        returnToTopLabel: "トップへ戻る",
        lastUpdatedText: "最終更新",
        outline: { level: [2, 3], label: "目次" },
        docFooter: { prev: "前へ", next: "次へ" },
        search: { provider: "local", options: { translations: { button: { buttonText: "検索", buttonAriaLabel: "検索" }, modal: { noResultsText: "結果が見つかりません", resetButtonTitle: "検索をクリア", footer: { selectText: "選択", navigateText: "切替", closeText: "閉じる" } } } } },
        editLink: { pattern: "https://github.com/wzh4869/AppPorts/edit/main/User_docs/docs/:path", text: "GitHub で編集" },
        socialLinks: [{ icon: "github", link: "https://github.com/wzh4869/AppPorts" }],
        nav: [
          { text: "ホーム", link: "/ja/" },
          { text: "クイックスタート", link: "/ja/faststart" },
          { text: "ダウンロード", link: "https://github.com/wzh4869/AppPorts/releases" },
          { text: "変更履歴", link: "/ja/changelog" },
        ],
        sidebar: [
          {
            text: "ガイド",
            items: [
              { text: "はじめに", link: "/ja/AppPorts" },
              { text: "クイックスタート", link: "/ja/faststart" },
              { text: "コア機能", link: "/ja/core" },
              { text: "ステータスバッジ", link: "/ja/badges" },
              { text: "データ移行", items: [
                { text: "基本実装", link: "/ja/datamigrae/baseinfo" },
                { text: "ツールディレクトリ検出", link: "/ja/datamigrae/tools" },
                { text: "操作ガイド", link: "/ja/datamigrae/operation" },
                { text: "再署名とクラッシュ防止", link: "/ja/datamigrae/resign" },
              ]},
              { text: "アプリ移行戦略", items: [
                { text: "移行戦略", link: "/ja/migration-strategy/portal" },
                { text: "アプリ種類と戦略対照", link: "/ja/migration-strategy/strategy-map" },
                { text: "自動更新検出", link: "/ja/migration-strategy/updater-detection" },
              ]},
              { text: "設定", link: "/ja/settings" },
              { text: "互換性と制限", link: "/ja/limitations" },
              { text: "トラブルシューティング", link: "/ja/troubleshooting" },
              { text: "よくある質問", link: "/ja/faq" },
              { text: "外部ストレージガイド", link: "/ja/storage-guide" },
              { text: "ログと診断", link: "/ja/logging" },
              { text: "変更履歴", link: "/ja/changelog" },
              { text: "コントリビューション", link: "/ja/contributing" },
            ],
          },
        ],
      },
    },

    ko: {
      label: "한국어",
      lang: "ko",
      title: "AppPorts",
      description: "사용자 가이드",
      themeConfig: {
        logo: "/logo.png",
        darkModeSwitchLabel: "테마",
        sidebarMenuLabel: "메뉴",
        returnToTopLabel: "맨 위로",
        lastUpdatedText: "마지막 업데이트",
        outline: { level: [2, 3], label: "이 페이지에서" },
        docFooter: { prev: "이전", next: "다음" },
        search: { provider: "local", options: { translations: { button: { buttonText: "검색", buttonAriaLabel: "검색" }, modal: { noResultsText: "검색 결과 없음", resetButtonTitle: "검색 초기화", footer: { selectText: "선택", navigateText: "전환", closeText: "닫기" } } } } },
        editLink: { pattern: "https://github.com/wzh4869/AppPorts/edit/main/User_docs/docs/:path", text: "GitHub에서 편집" },
        socialLinks: [{ icon: "github", link: "https://github.com/wzh4869/AppPorts" }],
        nav: [
          { text: "홈", link: "/ko/" },
          { text: "시작하기", link: "/ko/faststart" },
          { text: "다운로드", link: "https://github.com/wzh4869/AppPorts/releases" },
          { text: "변경 로그", link: "/ko/changelog" },
        ],
        sidebar: [
          {
            text: "가이드",
            items: [
              { text: "소개", link: "/ko/AppPorts" },
              { text: "시작하기", link: "/ko/faststart" },
              { text: "핵심 기능", link: "/ko/core" },
              { text: "상태 배지", link: "/ko/badges" },
              { text: "데이터 마이그레이션", items: [
                { text: "기본 구현", link: "/ko/datamigrae/baseinfo" },
                { text: "도구 디렉토리 감지", link: "/ko/datamigrae/tools" },
                { text: "작동 가이드", link: "/ko/datamigrae/operation" },
                { text: "재서명 및 크래시 방지", link: "/ko/datamigrae/resign" },
              ]},
              { text: "앱 마이그레이션 전략", items: [
                { text: "마이그레이션 전략", link: "/ko/migration-strategy/portal" },
                { text: "앱 유형과 전략 대照", link: "/ko/migration-strategy/strategy-map" },
                { text: "자동 업데이트 감지", link: "/ko/migration-strategy/updater-detection" },
              ]},
              { text: "설정", link: "/ko/settings" },
              { text: "호환성 및 제한사항", link: "/ko/limitations" },
              { text: "문제 해결", link: "/ko/troubleshooting" },
              { text: "자주 묻는 질문", link: "/ko/faq" },
              { text: "외부 저장소 가이드", link: "/ko/storage-guide" },
              { text: "로그 및 진단", link: "/ko/logging" },
              { text: "변경 로그", link: "/ko/changelog" },
              { text: "기여하기", link: "/ko/contributing" },
            ],
          },
        ],
      },
    },

    de: {
      label: "Deutsch",
      lang: "de",
      title: "AppPorts",
      description: "Benutzerhandbuch",
      themeConfig: {
        logo: "/logo.png",
        darkModeSwitchLabel: "Thema",
        sidebarMenuLabel: "Menü",
        returnToTopLabel: "Nach oben",
        lastUpdatedText: "Zuletzt aktualisiert",
        outline: { level: [2, 3], label: "Auf dieser Seite" },
        docFooter: { prev: "Zurück", next: "Weiter" },
        search: { provider: "local", options: { translations: { button: { buttonText: "Suchen", buttonAriaLabel: "Suchen" }, modal: { noResultsText: "Keine Ergebnisse", resetButtonTitle: "Suche löschen", footer: { selectText: "auswählen", navigateText: "wechseln", closeText: "schließen" } } } } },
        editLink: { pattern: "https://github.com/wzh4869/AppPorts/edit/main/User_docs/docs/:path", text: "Diese Seite auf GitHub bearbeiten" },
        socialLinks: [{ icon: "github", link: "https://github.com/wzh4869/AppPorts" }],
        nav: [
          { text: "Startseite", link: "/de/" },
          { text: "Schnellstart", link: "/de/faststart" },
          { text: "Download", link: "https://github.com/wzh4869/AppPorts/releases" },
          { text: "Änderungsprotokoll", link: "/de/changelog" },
        ],
        sidebar: [
          {
            text: "Handbuch",
            items: [
              { text: "Einführung", link: "/de/AppPorts" },
              { text: "Schnellstart", link: "/de/faststart" },
              { text: "Kernfunktionen", link: "/de/core" },
              { text: "Status-Badges", link: "/de/badges" },
              { text: "Datenmigration", items: [
                { text: "Grundlegende Implementierung", link: "/de/datamigrae/baseinfo" },
                { text: "Tool-Verzeichniserkennung", link: "/de/datamigrae/tools" },
                { text: "Betriebsanleitung", link: "/de/datamigrae/operation" },
                { text: "Signierung & Crash-Schutz", link: "/de/datamigrae/resign" },
              ]},
              { text: "Migrationsstrategie", items: [
                { text: "Migrationsstrategien", link: "/de/migration-strategy/portal" },
                { text: "App-Typen & Strategien", link: "/de/migration-strategy/strategy-map" },
                { text: "Auto-Update-Erkennung", link: "/de/migration-strategy/updater-detection" },
              ]},
              { text: "Einstellungen", link: "/de/settings" },
              { text: "Kompatibilität & Einschränkungen", link: "/de/limitations" },
              { text: "Fehlerbehebung", link: "/de/troubleshooting" },
              { text: "Häufige Fragen", link: "/de/faq" },
              { text: "Externer Speicherleitfaden", link: "/de/storage-guide" },
              { text: "Protokollierung & Diagnose", link: "/de/logging" },
              { text: "Änderungsprotokoll", link: "/de/changelog" },
              { text: "Beitragen", link: "/de/contributing" },
            ],
          },
        ],
      },
    },

    fr: {
      label: "Français",
      lang: "fr",
      title: "AppPorts",
      description: "Guide de l'utilisateur",
      themeConfig: {
        logo: "/logo.png",
        darkModeSwitchLabel: "Thème",
        sidebarMenuLabel: "Menu",
        returnToTopLabel: "Retour en haut",
        lastUpdatedText: "Dernière mise à jour",
        outline: { level: [2, 3], label: "Sur cette page" },
        docFooter: { prev: "Précédent", next: "Suivant" },
        search: { provider: "local", options: { translations: { button: { buttonText: "Rechercher", buttonAriaLabel: "Rechercher" }, modal: { noResultsText: "Aucun résultat", resetButtonTitle: "Effacer la recherche", footer: { selectText: "sélectionner", navigateText: "naviguer", closeText: "fermer" } } } } },
        editLink: { pattern: "https://github.com/wzh4869/AppPorts/edit/main/User_docs/docs/:path", text: "Modifier cette page sur GitHub" },
        socialLinks: [{ icon: "github", link: "https://github.com/wzh4869/AppPorts" }],
        nav: [
          { text: "Accueil", link: "/fr/" },
          { text: "Démarrage", link: "/fr/faststart" },
          { text: "Télécharger", link: "https://github.com/wzh4869/AppPorts/releases" },
          { text: "Journal des modifications", link: "/fr/changelog" },
        ],
        sidebar: [
          {
            text: "Guide",
            items: [
              { text: "Introduction", link: "/fr/AppPorts" },
              { text: "Démarrage rapide", link: "/fr/faststart" },
              { text: "Fonctionnalités", link: "/fr/core" },
              { text: "Badges de statut", link: "/fr/badges" },
              { text: "Migration de données", items: [
                { text: "Implémentation de base", link: "/fr/datamigrae/baseinfo" },
                { text: "Détection des répertoires", link: "/fr/datamigrae/tools" },
                { text: "Guide opérationnel", link: "/fr/datamigrae/operation" },
                { text: "Signature et prévention des crashes", link: "/fr/datamigrae/resign" },
              ]},
              { text: "Stratégie de migration", items: [
                { text: "Stratégies de migration", link: "/fr/migration-strategy/portal" },
                { text: "Types d'app et stratégies", link: "/fr/migration-strategy/strategy-map" },
                { text: "Détection des auto-mises à jour", link: "/fr/migration-strategy/updater-detection" },
              ]},
              { text: "Paramètres", link: "/fr/settings" },
              { text: "Compatibilité et limitations", link: "/fr/limitations" },
              { text: "Dépannage", link: "/fr/troubleshooting" },
              { text: "FAQ", link: "/fr/faq" },
              { text: "Guide de stockage externe", link: "/fr/storage-guide" },
              { text: "Journalisation et diagnostic", link: "/fr/logging" },
              { text: "Journal des modifications", link: "/fr/changelog" },
              { text: "Contribuer", link: "/fr/contributing" },
            ],
          },
        ],
      },
    },

    es: {
      label: "Español",
      lang: "es",
      title: "AppPorts",
      description: "Guía del usuario",
      themeConfig: {
        logo: "/logo.png",
        darkModeSwitchLabel: "Tema",
        sidebarMenuLabel: "Menú",
        returnToTopLabel: "Volver arriba",
        lastUpdatedText: "Última actualización",
        outline: { level: [2, 3], label: "En esta página" },
        docFooter: { prev: "Anterior", next: "Siguiente" },
        search: { provider: "local", options: { translations: { button: { buttonText: "Buscar", buttonAriaLabel: "Buscar" }, modal: { noResultsText: "Sin resultados", resetButtonTitle: "Limpiar búsqueda", footer: { selectText: "seleccionar", navigateText: "cambiar", closeText: "cerrar" } } } } },
        editLink: { pattern: "https://github.com/wzh4869/AppPorts/edit/main/User_docs/docs/:path", text: "Editar esta página en GitHub" },
        socialLinks: [{ icon: "github", link: "https://github.com/wzh4869/AppPorts" }],
        nav: [
          { text: "Inicio", link: "/es/" },
          { text: "Inicio rápido", link: "/es/faststart" },
          { text: "Descargar", link: "https://github.com/wzh4869/AppPorts/releases" },
          { text: "Registro de cambios", link: "/es/changelog" },
        ],
        sidebar: [
          {
            text: "Guía",
            items: [
              { text: "Introducción", link: "/es/AppPorts" },
              { text: "Inicio rápido", link: "/es/faststart" },
              { text: "Funciones principales", link: "/es/core" },
              { text: "Insignias de estado", link: "/es/badges" },
              { text: "Migración de datos", items: [
                { text: "Implementación básica", link: "/es/datamigrae/baseinfo" },
                { text: "Detección de directorios", link: "/es/datamigrae/tools" },
                { text: "Guía de operaciones", link: "/es/datamigrae/operation" },
                { text: "Firmado y prevención de fallos", link: "/es/datamigrae/resign" },
              ]},
              { text: "Estrategia de migración", items: [
                { text: "Estrategias de migración", link: "/es/migration-strategy/portal" },
                { text: "Tipos de app y estrategias", link: "/es/migration-strategy/strategy-map" },
                { text: "Detección de auto-actualización", link: "/es/migration-strategy/updater-detection" },
              ]},
              { text: "Configuración", link: "/es/settings" },
              { text: "Compatibilidad y limitaciones", link: "/es/limitations" },
              { text: "Solución de problemas", link: "/es/troubleshooting" },
              { text: "Preguntas frecuentes", link: "/es/faq" },
              { text: "Guía de almacenamiento externo", link: "/es/storage-guide" },
              { text: "Registro y diagnóstico", link: "/es/logging" },
              { text: "Registro de cambios", link: "/es/changelog" },
              { text: "Contribuir", link: "/es/contributing" },
            ],
          },
        ],
      },
    },
  },
});
